### ISSUE TITLE
[DOC] Review Wikipedia

### ISSUE THREAD

**Issue by GregorSchroeder** [SANDAG/Cohort-Component-Model#37]
**Describe the documentation fix or enhancement.**
The Cohort Component Model has reached an "alpha" state. Although it has missing functionalities, it is able to be run in full and includes a full Wikipedia. Please review the project Wikipedia linked below and identify errors, inconsistencies, missing portions, or parts that require further clarification/explanation in this issue thread.

https://github.com/SANDAG/Cohort-Component-Model/wiki

**Comment by SarahHudson-SANDAG** [comment]
In the title, is it correct to include Estimates or should it just say Forecast? CCM is only used in Forecast.

**Comment by SarahHudson-SANDAG** [comment]
The "M" in CCM seems to be interchangeably used for Model, Method, or Module. Just clarifying that.

**Comment by SarahHudson-SANDAG** [comment]
Why are a few items highlighted in yellow in the figure?

**Comment by GregorSchroeder** [comment]
Hi @SarahHudson-SANDAG, please review my response to each of your comments and the changes in the Wiki made, where applicable.

1. Refers to our team name "SANDAG ESTIMATES & FORECAST" ascribing ownership of the Cohort Component Model to the E&F team. Recommendation is no change.
2. I agree this is confusing. I have removed all "CCM" acronym references and am now using full names where possible.
3. The yellow highlighted items are the main outputs from the annual cycle; population, households/gqs, and then the input population for the next cycle. I wanted to draw attention to these.
4. Corrected.
5. Added some clarifying language. The base year is set depending on the launch year and is tied to decennial Census, or for 2020 blended data, population data that is then incremented up to the launch year and beyond to the horizon year of the forecast.
6. Added a [new Wikipedia page](https://github.com/SANDAG/Cohort-Component-Model/wiki/Model-Outputs) describing the outputs of the model.
7. This is actually a repository wide issue with the naming convention of the "Native Hawaiian or Other Pacific Islander alone" race/ethnicity category. It is erroneously labelled "Native Hawaiian and Other Pacific Islander alone" throughout the codebase. This will require a bug-fix. **TODO: Link Bug Issue here**
8. Fixed.
9. Added background.
10. Households of size 1, 2, and 3+ cover all possible households. There are no 0 person households and 3+ goes from 3 to infinity. Thus, their rates should sum to 1 as the groups are exclusive and cover the entire universe of households.
11. Added a little clarification.

**Comment by SarahHudson-SANDAG** [comment]
Everything looks good.
Very minor suggestion, remove the periods at the end of each phrase in the tables. https://github.com/SANDAG/Cohort-Component-Model/wiki/Model-Outputs
