### ISSUE TITLE
[FEATURE] ETL process to save csv to SQL database

### ISSUE THREAD

**Issue by nmad-sandag** [SANDAG/Cohort-Component-Model#70]
Is your feature request related to a problem? Please describe.
There is no ETL (Extract, Transform, Load) process to automate the transfer of data from the output CSV files to the newly established SQL database.

Describe the solution you'd like
Implement an ETL process, so the model run data is tracked and the process can aid in data management, and also streamline the reporting process.

**Comment by GregorSchroeder** [comment]
The description of this issue solely refers to the database build, which has been completed in #65. The description should talk about how a database build has been completed and now an ETL process needs to be created. @nmad-sandag please correct the description of this issue.
